// 文字列表滚动数据
export const deals = [
    {
        area: '1郑州市荣阳 ',
        sellerName: '益博农资用品批发店',
        productType: '杀虫剂',
    },
    { area: '2定西市岷县', sellerName: '新鑫中药材', productType: '黄芪' },
    {
        area: '3湘西土家族 ',
        sellerName: '湖南湘西猕猴桃苗木基地',
        productType: '砧木',
    },
    {
        area: '4周口市鹿邑 ',
        sellerName: '蒲公英直供中心',
        productType: '花草茶',
    },
    { area: '5昌吉回族自 ', sellerName: '自己销售', productType: '海棠果' },
    {
        area: '6南宁市西乡 ',
        sellerName: '溪山鲜果产地直供',
        productType: '香蕉',
    },
    { area: '7赣州市信丰 ', sellerName: '美物源农业', productType: '橙子' },
    { area: '8永州市江永 ', sellerName: '夏梦秋果业', productType: '柑桔' },
    {
        area: '9达拉特旗',
        sellerName: '兴安盟农人上品科技有限公司',
        productType: '玉米',
    },
    { area: '10', sellerName: '夏梦秋果业', productType: '柑桔' },
    {
        area: '12',
        sellerName: '兴安盟农人上品科技有限公司',
        productType: '玉米',
    },
];
// 蔬菜分类 左栏

export const vegetables = [
    {
        name: '葱姜蒜类',
        items: [
            '韭菜',
            '蒜苗',
            '大蒜',
            '生菜',
            '大葱',
            '小葱',
            '蒜苔',
            '洋葱',
            '藠头',
            '洋姜',
            '葱仔',
            '韭菜',
            '野蒜',
            '阳荷',
            '红球姜',
            '沙姜',
            '山姜',
            '南姜',
            '风姜',
            '沙葱',
        ],
    },
    {
        name: '叶菜类',
        items: [
            '白菜',
            '小白菜',
            '生菜',
            '菠菜',
            '娃娃菜',
            '木耳菜',
            '香菜',
            '油麦菜',
            '空心菜',
            '菠菜',
            '萝卜菜',
            '芹菜',
            '莴笋',
            '芥菜',
            '菜苔',
            '儿菜',
        ],
    },
    {
        name: '茄果菜类',
        items: ['辣椒', '西红柿', '茄子', '秋葵', '鲜玉米', '玉米笋'],
    },
    {
        name: '食用菌',
        items: [
            '松树菌',
            '元蘑',
            '珊瑚菌',
            '鹿茸菇',
            '栗蘑',
            '龙爪菇',
            '荷灵菇',
            '海鲜菇',
            '毛尖蘑',
            '姬菇',
            '褐蘑',
            '鸡腿菇',
            '竹荪',
            '紫花菌',
            '白灵菇',
            '灵芝菇',
        ],
    },
    {
        name: '蔬菜分类1',
        items: [
            '蔬菜1A',
            '蔬菜1B',
            '蔬菜1C',
            '蔬菜1D',
            '蔬菜1E',
            '蔬菜1F',
            '蔬菜1G',
            '蔬菜1H',
            '蔬菜1I',
            '蔬菜1J',
            '蔬菜1K',
            '蔬菜1L',
            '蔬菜1M',
            '蔬菜1N',
            '蔬菜1O',
            '蔬菜1P',
            '蔬菜1Q',
            '蔬菜1R',
        ],
    },
    {
        name: '蔬菜分类2',
        items: [
            '蔬菜2A',
            '蔬菜2B',
            '蔬菜2C',
            '蔬菜2D',
            '蔬菜2E',
            '蔬菜2F',
            '蔬菜2G',
            '蔬菜2H',
            '蔬菜2I',
            '蔬菜2J',
            '蔬菜2K',
            '蔬菜2L',
            '蔬菜2M',
            '蔬菜2N',
            '蔬菜2O',
            '蔬菜2P',
            '蔬菜2Q',
            '蔬菜2R',
        ],
    },
    {
        name: '蔬菜',
    },
];

export const agriculture = [
    {
        name: '农用机械设备',
        items: [
            '农用拖拉机',
            '农机配件',
            '耕整机',
            '食品加工机械',
            '果蔬机械',
            '植保机',
            '饲料机',
            '肥料机械',
            '发电设备',
            '屠宰及肉类加工设备',
            '食用菌机械',
        ],
    },
    {
        name: '肥料',
        items: [
            '复合肥',
            '缓释肥',
            '螯合肥料',
            '单质肥',
            '生物肥',
            '水溶肥',
            '叶面肥',
            '有机肥',
            '间接肥料',
            '果实着色剂',
            '肥料套餐',
        ],
    },
    {
        name: '农药',
        items: [
            '杀虫剂',
            '杀菌剂',
            '杀螨剂',
            '除草剂',
            '生物农药',
            '植物生长调节剂',
            '助剂',
            '农药套餐',
            '拌种剂',
        ],
    },
    {
        name: '饲料',
        items: [
            '青绿饲料',
            '预混料',
            '宠物饲料',
            '饼粕饲料',
            '蛋白质补充饲料',
            '干草类饲料',
            '谷物饲料',
            '秸秆饲料',
            '糠麸类饲料',
            '矿物质饲料',
            '配合饲料',
            '青贮饲料',
            '糟渣类饲料',
            '发酵饲料',
            '饲料添加剂',
        ],
    },
    {
        name: '农用百货',
        items: [
            '农用工具',
            '渔具',
            '劳保用品',
            '硫磺粉',
            '保水剂',
            '不锈钢管',
            '热熔胶',
            '塑料膜',
            '护栏',
            '栽培基质',
            '活性花粉',
            '炭',
            '木材',
            '养殖百货',
            '育苗防护资材',
            '园林管理资材',
        ],
    },
    {
        name: '排灌设备',
        items: [
            '涵管',
            '管材管件',
            '滴灌喷灌',
            '过滤设备',
            '灌溉设备',
            '泵',
            '格栅',
            '排水板',
            '蓄水板',
        ],
    },
    {
        name: '农资农具',
        title: '产地直发 海量供应',
    },
];

export const grain = [
    {
        name: '食用油',
        items: [
            '松子油',
            '牛油果油',
            '山茶油',
            '花生油',
            '橄榄油',
            '玉米油',
            '菜籽油',
            '葵花籽油',
            '色拉油',
            '火麻油',
            '亚麻籽油',
            '红花籽油',
            '核桃油',
            '秋葵油',
        ],
    },
    {
        name: '调味品',
        items: [
            '菌油',
            '味精',
            '鸡精',
            '糖',
            '醋',
            '酱油',
            '蚝油',
            '调味酱',
            '剁椒',
            '调味油',
            '料酒',
            '火锅底料',
            '调味料',
            '香茅',
            '汤料',
            '泡椒',
            '卤料',
            '花生碎',
        ],
    },
    {
        name: '香辛料',
        items: [
            '桂子',
            '千里香',
            '莳萝子',
            '胡椒粉',
            '杜松子',
            '百里香',
            '干辣椒',
            '辣椒粉',
            '胡椒',
            '孜然',
            '花椒',
            '桂皮',
            '陈皮',
            '八角',
            '姜粉',
            '香砂仁',
            '香草',
        ],
    },
    {
        name: '谷物粉淀粉',
        items: [
            '淀粉',
            '面粉',
            '粘米粉',
            '黄豆面',
            '燕麦粉',
            '马蹄粉',
            '高粱面粉',
            '玉米面',
            '豆面',
            '红豆粉',
            '糯米粉',
            '木薯粉',
            '红薯干粉',
            '绿豆粉',
            '黍米粉',
        ],
    },
    {
        name: '豆制品',
        items: [
            '霉豆渣',
            '豆豉',
            '豆腐',
            '香干',
            '腐乳',
            '千张',
            '兰花干',
            '素鸡',
            '腐竹',
            '豆腐皮',
            '蛋白肉',
            '食用豆饼',
            '腊八豆',
            '豆笋',
            '豆钱子',
            '豆卷',
            '纳豆',
        ],
    },
    {
        name: '面食米食',
        items: [
            '饽饽',
            '凉糕',
            '肠粉',
            '锅贴',
            '西米',
            '馒头',
            '焖子',
            '面条',
            '饺子',
            '汤圆',
            '包子',
            '烧麦',
            '面筋',
            '馄饨',
            '面花',
            '凉皮',
            '凉粉',
            '饺子皮',
            '馄饨皮',
        ],
    },
    {
        name: '粮米油面',
    },
];

export const seeds = [
    {
        name: '水果种苗',
        items: [
            '蔓越莓苗',
            '红果仔苗',
            '巴婆果苗',
            '姑娘果苗',
            '荸荠种苗',
            '猴脑果苗',
            '苹果树苗',
            '梨树苗',
            '西瓜苗',
            '猕猴桃苗',
            '桃树苗',
            '柑桔苗',
            '柚树苗',
        ],
    },
    {
        name: '花草类种子',
        items: [
            '石菖蒲种子',
            '莳萝种子',
            '蓬蒿菊种子',
            '兔尾草种子',
            '凉粉草种子',
            '异果菊种子',
            '翠珠花种子',
            '球吉莉种子',
            '樱雪轮种子',
            '蓍草种子',
        ],
    },
    {
        name: '蔬菜种子',
        items: [
            '山麻植种子',
            '春菜种子',
            '碱蓬草种子',
            '小根蒜种子',
            '山葵种子',
            '豆角种子',
            '花椒种子',
            '香菜种子',
            '芹菜种子',
            '韭菜种子',
            '苦苣种子',
        ],
    },
    {
        name: '水果类种子',
        items: [
            '星苹果种子',
            '黄晶果种子',
            '嘉宝果种子',
            '刺梨种子',
            '人参果种子',
            '菠萝蜜种子',
            '芒果种子',
            '柠檬种子',
            '蓝莓种子',
            '李子种子',
            '柿子种子',
        ],
    },
    {
        name: '粮油类种子',
        items: [
            '意米种子',
            '油菜种子',
            '花生种子',
            '高梁种子',
            '油菜籽种子',
            '小麦种子',
            '藜麦种子',
            '黄豆种子',
            '蓖麻种子',
            '大麦种子',
            '青稞种子',
            '燕麦种子',
        ],
    },
    {
        name: '苗木类种子',
        items: [
            '薜荔种子',
            '羊柴种子',
            '火力楠种子',
            '壳菜果种子',
            '砂生槐种子',
            '蒜头果种子',
            '柘树种子',
            '漆树种子',
            '山胡椒种子',
            '羊蹄甲种子',
        ],
    },
    {
        name: '种子种苗',
    },
];
export const Agricultural = [
    {
        name: '干果坚果',
        items: [
            '榄钱',
            '柿饼',
            '红枣',
            '枸杞',
            '核桃',
            '瓜子',
            '板栗',
            '葡萄干',
            '桂圆干',
            '山楂干',
            '白果',
            '芡实',
            '榛子',
            '巴旦木',
            '杏仁',
            '沙漠果',
            '香榧',
            '开心果',
        ],
    },
    {
        name: '茶叶',
        items: [
            '黑茶',
            '普洱',
            '乌龙茶',
            '绿茶',
            '红茶',
            '花草茶',
            '黄茶',
            '白茶',
            '茶粉',
        ],
    },
    {
        name: '肉制品加工',
        items: [
            '熟羊肉',
            '火腿',
            '腊肉',
            '板鸭',
            '肉卷',
            '腌咸鸭',
            '腌咸肉',
            '腌咸鹅',
            '甲鱼干',
            '籽乌干',
            '章鱼干',
            '鱼鳞干',
            '鱿鱼干',
            '腌咸螺',
            '蚬子干',
            '腌咸鸡',
            '烧鸡',
            '卤鸭',
            '熟牛肉',
            '熟鸡肉',
            '熟鸽肉',
            '熟鹅肉',
            '腊羊肉',
        ],
    },
    {
        name: '水产加工',
        items: [
            '甲鱼干',
            '籽乌干',
            '章鱼干',
            '鱼鳞干',
            '鱿鱼干',
            '腌咸螺',
            '蚬子干',
            '腌咸虾',
            '虾仁',
            '虾皮',
            '虾干',
            '沙虫干',
            '墨鱼干',
            '卤甲鱼',
            '龙须菜干',
        ],
    },
    {
        name: '营养滋补',
        items: ['蜂蜜', '花粉', '桃胶', '雪燕', '皂角米', '鱼鳔', '蜂王浆'],
    },
    {
        name: '速食食品',
        items: [
            '速冻蔬果',
            '饼干糕点',
            '蜜饯果脯',
            '休闲零食',
            '罐头',
            '方便食品',
            '糖果',
            '丸滑类',
            '冲饮',
        ],
    },
    {
        name: '农副加工',
    },
];
// 蔬菜分类 右栏
export const supplies = [
    { name: '长白大葱', price: '1.5', unit: '斤' },
    { name: '线椒原产地供应', price: '3.5', unit: '斤' },
    { name: '扁豆原产地供应', price: '1.8', unit: '斤' },
    { name: '云南昭通镇雄县新鲜白萝卜', price: '1800', unit: '吨' },
    { name: '胡萝卜', price: '1', unit: '斤' },
    { name: '上海青浦广东菜心', price: '3', unit: '斤' },
    { name: '黄心娃娃菜', price: '1.9', unit: '斤' },
    { name: '云南昭通镇雄县新鲜白萝卜', price: '1800', unit: '吨' },
];
export const machinery = [
    {
        name: '精草铵磷铵盐广谱内吸除草剂除灭一年生和多年生杂草',
        price: '15',
        unit: '瓶',
    },
    {
        name: '2024湖北江陵新稻草二次加工过风选无土无杂质',
        price: '688',
        unit: '吨',
    },
    {
        name: '15%烯效唑悬浮剂花椒树控梢控旺调节生长植株健壮',
        price: '50',
        unit: '瓶',
    },
    { name: '电动搬运叉车', price: '28500', unit: '辆' },
    {
        name: '益生菌发酵大豆纯黄豆发酵大豆底肥发酵黄豆',
        price: '96',
        unit: '袋',
    },
    {
        name: '新款摘花椒器花椒采摘专用器防刺手套剪花椒神器',
        price: '19.8',
        unit: '把',
    },
    {
        name: '逆能量有机水溶肥解盐碱调理土壤缓解重茬及连作障碍',
        price: '180',
        unit: '件',
    },
];
export const rice = [
    {
        name: '黄剁辣椒坛香剁椒源头产地直供湖南剁辣椒...',
        price: '2.99',
        unit: '斤',
    },
    { name: '八角大茴香大料', price: '28', unit: '斤' },
    {
        name: '莳萝子莳实落子石落子石萝子莳梦落子落子萝子',
        price: '38',
        unit: '斤',
    },
    { name: '长沙市雨花区大量批发供应各类优质大米', price: '2.2', unit: '斤' },
    { name: '五常大米河水灌溉黑土地农户自产自销', price: '68', unit: '斤' },
    {
        name: '农家自种自己加工的嘎嘎纯嘎板正的红薯...',
        price: '13',
        unit: '斤',
    },
    { name: '芭蕉芋淀粉', price: '9000', unit: '吨' },
];
export const seedlings = [
    { name: '花牛苹果树苗蛇果树苗当年挂果', price: '4.8', unit: '棵' },
    { name: '丑苹果树苗苹果树苗南北方都可种植', price: '4.8', unit: '棵' },
    {
        name: '楠木苗直发贵州毕节健康种苗安心种植绿化...',
        price: '0.5',
        unit: '棵',
    },
    { name: '贵州省优质薄皮核桃苗供应大方县直发', price: '0.6', unit: '棵' },
    { name: '贵州省大方县高品质杉木树苗供应', price: '0.18', unit: '棵' },
    { name: '红美人三年苗杉木苗供应', price: '40', unit: '棵' },
    { name: '大量出售蜂糖李苗直生苗嫁接苗', price: '8', unit: '棵' },
];
export const sideline = [
    {
        name: '广西钦州特产新鲜嫩黄瓜皮下饭菜农家腌制香...',
        price: '5.8',
        unit: '斤',
    },
    {
        name: '广西广东特产年份黑老菜脯老萝卜干自制农...',
        price: '8.5',
        unit: '斤',
    },
    {
        name: '卜豆角精品源头产地地扑豆角曝豆角下饭菜湖南...',
        price: '3.99',
        unit: '斤',
    },
    {
        name: '长沙面包 糖渣 提供饲料厂 养殖户好帮手',
        price: '2400',
        unit: '吨',
    },
    {
        name: '武汉面包',
        price: '2000',
        unit: '吨',
    },
    {
        name: '枣夹腰果网红腰果泡芙奶酪奶香夹心腰果奶...',
        price: '18',
        unit: '斤',
    },
    {
        name: '陇康土蜂蜜，一年取一次蜜',
        price: '60',
        unit: '斤',
    },
];

// 好物推荐
export const products = [
    // 第一组 索引 0
    {
        image: new URL('@/assets/images/supply/1.jpg', import.meta.url).href,
        title: '广西/云南黄金水果玉米新鲜发货3/5/9斤一件代发包邮批发',
        price: '16.80',
        unit: '箱',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/2.jpg', import.meta.url).href,
        title: '北虫草 【500g大孢子头】虫草虫草花金虫草蛹虫草干货泡茶',
        price: '4.60',
        unit: '包',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/3.jpg', import.meta.url).href,
        title: '古田丑耳3朵试吃装',
        price: '11.90',
        unit: '包',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/4.jpg', import.meta.url).href,
        title: '黑木耳 富贵干货大礼包B款，年货送礼高档礼盒装',
        price: '59.00',
        unit: '袋',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/5.jpg', import.meta.url).href,
        title: '福建古田银耳现摘现发古田白木耳易糯多胶，1朵100G左右',
        price: '3.00',
        unit: '朵',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/6.jpg', import.meta.url).href,
        title: '蒙阴紫罗兰紫薯-皮薄肉细，软糯香甜，口口惊艳，好吃到惊讶',
        price: '14.50',
        unit: '袋',
        description: '成交45元',
    },
];
export const equipment = [
    {
        image: new URL('@/assets/images/supply/7.jpg', import.meta.url).href,
        title: '80%代森锰锌1000克 代森猛锌辛杀菌剂早疫病黑星病炭疽病',
        price: '31.80',
        unit: '袋',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/8.jpg', import.meta.url).href,
        title: '颗粒锌 田当家EDTA螯合锌微量元素叶面肥糖醇小分子锌小叶黄',
        price: '28.00',
        unit: '袋',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/9.jpg', import.meta.url).href,
        title: '飞防专用助剂航空植保无人机增效剂防漂移促沉降强渗透耐冲刷',
        price: '55.00',
        unit: '瓶',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/10.jpg', import.meta.url).href,
        title: '36%春雷喹啉铜溃疡病角斑病软腐病稻瘟病细菌病害专用杀菌剂',
        price: '2.00',
        unit: '袋',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/11.jpg', import.meta.url).href,
        title: '0.5%阿维菌素颗粒剂 阿维菌素农药黄瓜根结线虫杀虫剂',
        price: '3.00',
        unit: '袋',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/12.jpg', import.meta.url).href,
        title: '蒙阴紫罗兰紫薯-皮薄肉细，软糯香甜，口口惊艳，好吃到惊讶',
        price: '11.80',
        unit: '袋',
        description: '成交45元',
    },
];
export const noodles = [
    {
        image: new URL('@/assets/images/supply/13.jpg', import.meta.url).href,
        title: '梅花椒 韩城大红袍梅花花椒产地直销包邮',
        price: '31.80',
        unit: '斤',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/14.jpg', import.meta.url).href,
        title: '【东北燕麦米】燕麦仁农家裸燕麦新米胚芽米燕麦粒杂粮粗粮包邮',
        price: '3.29',
        unit: '袋',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/15.jpg', import.meta.url).href,
        title: '大红袍花椒 陕西2024新大红袍，红花椒颗粒。开口98以上',
        price: '55.00',
        unit: '斤',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/16.jpg', import.meta.url).href,
        title: '玉米油5升新疆纯正玉米物理压榨营养浓香食用油批发',
        price: '69.00',
        unit: '桶',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/17.jpg', import.meta.url).href,
        title: '包邮~内蒙古敖汉旗有机四色小米黑小米绿小米黄小米白小米',
        price: '36.00',
        unit: '袋',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/18.jpg', import.meta.url).href,
        title: '蒜蓉剁椒10斤/桶，烤生蚝茄子小龙虾调味料，48小时发货',
        price: '99.80',
        unit: '桶',
        description: '成交45元',
    },
];
export const planting = [
    {
        image: new URL('@/assets/images/supply/19.jpg', import.meta.url).href,
        title: '红树莓苗 天然绿色养生水果树莓',
        price: '3.00',
        unit: '株',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/20.jpg', import.meta.url).href,
        title: '凯撒大帝西芹种子净含量100克大颗芹菜 不空心口感好',
        price: '60.00',
        unit: '罐',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/21.jpg', import.meta.url).href,
        title: '神秘果苗 四季开花结果，当年种当年挂果，5年苗带营养袋发货',
        price: '89.00',
        unit: '株',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/22.jpg', import.meta.url).href,
        title: '野菊花种子多年生野黄色菊花山坡路边野生花种籽子室外易活盆栽',
        price: '1.50',
        unit: '袋',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/23.jpg', import.meta.url).href,
        title: '红蕉苗',
        price: '7.50',
        unit: '株',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/24.jpg', import.meta.url).href,
        title: '基地直发木春菊苗 绿化工程苗 四季开花 庭院种植 盆栽苗',
        price: '0.60',
        unit: '棵',
        description: '成交45元',
    },
];
export const processing = [
    {
        image: new URL('@/assets/images/supply/25.jpg', import.meta.url).href,
        title: '茶友们正山小种红茶正宗浓香型2024新茶叶礼盒装散装500g',
        price: '188.00',
        unit: '斤',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/26.jpg', import.meta.url).href,
        title: '涪陵榨菜手工榨菜218克装',
        price: '3.08',
        unit: '瓶',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/27.jpg', import.meta.url).href,
        title: '草鱼条 地摊 电商 批发 精品草鱼条干 干草鱼 鱼干 干鱼',
        price: '9.00',
        unit: '斤',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/28.jpg', import.meta.url).href,
        title: '新疆红枣片 500g一包',
        price: '14.90',
        unit: '斤',
        description: '成交45元',
    },
    {
        image: new URL('@/assets/images/supply/29.jpg', import.meta.url).href,
        title: '味哲熊猫版螺蛳粉8袋*315g',
        price: '19.00',
        unit: '箱',
        description: '成交8.3万元',
    },
    {
        image: new URL('@/assets/images/supply/30.jpg', import.meta.url).href,
        title: '包邮~新疆喀什疆果果中秋节礼盒新疆特产坚果干果悦味',
        price: '99.80',
        unit: '箱',
        description: '成交45元',
    },
];
